<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.likerhood.design</groupId>
    <artifactId>CodeDesignWork</artifactId>
    <version>1.0-SNAPSHOT</version>

    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <fastjson.version>1.2.62</fastjson.version>
        <lombok.version>1.18.30</lombok.version>
    </properties>

    <modules>
        <module>codedesign1.0-0</module>
        <module>codedesign1.0-1</module>
        <module>codedesign1.0-2</module>
        <module>codedesign1.1-0</module>
        <module>codedesign1.1-1</module>
        <module>codedesign1.2-0</module>
        <module>codedesign2.0-0</module>
        <module>codedesign2.0-1</module>
        <module>codedesign2.0-2</module>
        <module>codedesign3.0-0</module>
        <module>codedesign3.0-1</module>
        <module>codedesign3.0-3</module>
        <module>codedesign4.0-0</module>
        <module>codedesign5.0-0</module>
        <module>codedesign5.0-1</module>
        <module>codedesign5.0-2</module>
        <module>codedesign5.1-0</module>
        <module>codedesign5.1-1</module>
        <module>codedesign5.1-2</module>
        <module>codedesign6.0-0</module>
        <module>codedesign6.0-1</module>
        <module>codedesign7.0-0</module>
        <module>codedesign7.0-1</module>
        <module>codedesign8.0-0</module>
        <module>codedesign8.0-1</module>
        <module>codedesign8.0-2</module>
        <module>codedesign9.0-0</module>
        <module>codedesign10.0-0</module>
        <module>codedesign10.0-1</module>
        <module>codedesign11.0-0</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>fastjson</artifactId>
                <version>${fastjson.version}</version>
            </dependency>

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
                <scope>provided</scope>
            </dependency>



        </dependencies>
    </dependencyManagement>

</project>